function fIn=SetMicroscopicBCOutletPressure(ux,uy,fIn,rho,outlet_node_list)

% microscopic boundary conditions outlet
    fIn(outlet_node_list,4)=fIn(outlet_node_list,2)-...
        (2/3)*rho(outlet_node_list).*ux(outlet_node_list);
    fIn(outlet_node_list,8)=fIn(outlet_node_list,6)+...
        (1/2)*(fIn(outlet_node_list,3)-fIn(outlet_node_list,5))...
        +(1/2)*rho(outlet_node_list).*uy(outlet_node_list)...
        -(1/6)*rho(outlet_node_list).*ux(outlet_node_list);
    fIn(outlet_node_list,7)=fIn(outlet_node_list,9)+...
        (1/2)*(fIn(outlet_node_list,5)-fIn(outlet_node_list,3))...
        +(1/2)*rho(outlet_node_list).*uy(outlet_node_list)...
        -(1/6)*rho(outlet_node_list).*ux(outlet_node_list);