function [ux,uy,rho]=SetOutletMacroscopicBCConstPress(ux,uy,rho,fIn,...
    rho_out,outlet_node_list)

% set macroscopic outlet boundary conditions
    rho(outlet_node_list) = rho_out;
    ux(outlet_node_list) = -1 + 1./(rho(outlet_node_list)) .* (...
        fIn(outlet_node_list,1)+fIn(outlet_node_list,3)+...
        fIn(outlet_node_list,5)+ 2*(fIn(outlet_node_list,2) + ...
        fIn(outlet_node_list,6)+fIn(outlet_node_list,9)));
    uy(outlet_node_list) = 0;